// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CoffeeManagement.Flow4.Repositories.Models;
using Microsoft.EntityFrameworkCore;

namespace CoffeeManagement.Flow4.Repositories.DBContext;

public partial class CoffeeManagementContext : DbContext
{
    public CoffeeManagementContext()
    {
    }

    public CoffeeManagementContext(DbContextOptions<CoffeeManagementContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BusinessManager> BusinessManagers { get; set; }

    public virtual DbSet<Farmer> Farmers { get; set; }

    public virtual DbSet<Inventory> Inventories { get; set; }

    public virtual DbSet<InventoryLog> InventoryLogs { get; set; }

    public virtual DbSet<ProcessingBatch> ProcessingBatches { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Warehouse> Warehouses { get; set; }

    public virtual DbSet<WarehouseInboundRequest> WarehouseInboundRequests { get; set; }

    public virtual DbSet<WarehouseOutboundReceipt> WarehouseOutboundReceipts { get; set; }

    public virtual DbSet<WarehouseOutboundRequest> WarehouseOutboundRequests { get; set; }

    public virtual DbSet<WarehouseReceipt> WarehouseReceipts { get; set; }

    public virtual DbSet<YieldAllocation> YieldAllocations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BusinessManager>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Business__B9BE370F07FB7C59");

            entity.Property(e => e.UserId)
                .ValueGeneratedNever()
                .HasColumnName("user_id");
            entity.Property(e => e.CompanyName)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("company_name");
            entity.Property(e => e.Position)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("position");

            entity.HasOne(d => d.User).WithOne(p => p.BusinessManager)
                .HasForeignKey<BusinessManager>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BusinessM__user___44FF419A");
        });

        modelBuilder.Entity<Farmer>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Farmers__B9BE370F36673083");

            entity.Property(e => e.UserId)
                .ValueGeneratedNever()
                .HasColumnName("user_id");
            entity.Property(e => e.CertificationStatus)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("certification_status");
            entity.Property(e => e.DateOfBirth).HasColumnName("date_of_birth");
            entity.Property(e => e.FarmLocation)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("farm_location");
            entity.Property(e => e.FarmSize).HasColumnName("farm_size");
            entity.Property(e => e.FullName)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("full_name");

            entity.HasOne(d => d.User).WithOne(p => p.Farmer)
                .HasForeignKey<Farmer>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Farmers__user_id__4222D4EF");
        });

        modelBuilder.Entity<Inventory>(entity =>
        {
            entity.HasKey(e => e.InventoryId).HasName("PK__Inventor__B59ACC49774D076C");

            entity.Property(e => e.InventoryId)
                .ValueGeneratedNever()
                .HasColumnName("inventory_id");
            entity.Property(e => e.BatchId).HasColumnName("batch_id");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.Unit)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("unit");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.WarehouseId).HasColumnName("warehouse_id");

            entity.HasOne(d => d.Batch).WithMany(p => p.Inventories)
                .HasForeignKey(d => d.BatchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Inventori__batch__5DCAEF64");

            entity.HasOne(d => d.Warehouse).WithMany(p => p.Inventories)
                .HasForeignKey(d => d.WarehouseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Inventori__wareh__5CD6CB2B");
        });

        modelBuilder.Entity<InventoryLog>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK__Inventor__9E2397E0E30BB236");

            entity.Property(e => e.LogId)
                .ValueGeneratedNever()
                .HasColumnName("log_id");
            entity.Property(e => e.ActionType)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("action_type");
            entity.Property(e => e.InventoryId).HasColumnName("inventory_id");
            entity.Property(e => e.LoggedAt)
                .HasColumnType("datetime")
                .HasColumnName("logged_at");
            entity.Property(e => e.Note)
                .HasColumnType("text")
                .HasColumnName("note");
            entity.Property(e => e.QuantityChanged).HasColumnName("quantity_changed");
            entity.Property(e => e.TriggeredBySystem)
                .HasDefaultValue(false)
                .HasColumnName("triggered_by_system");
            entity.Property(e => e.UpdatedBy).HasColumnName("updated_by");

            entity.HasOne(d => d.Inventory).WithMany(p => p.InventoryLogs)
                .HasForeignKey(d => d.InventoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Inventory__inven__60A75C0F");
        });

        modelBuilder.Entity<ProcessingBatch>(entity =>
        {
            entity.HasKey(e => e.BatchId).HasName("PK__Processi__DBFC04317B0F425F");

            entity.Property(e => e.BatchId)
                .ValueGeneratedNever()
                .HasColumnName("batch_id");
            entity.Property(e => e.BatchCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("batch_code");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CropSeasonId).HasColumnName("crop_season_id");
            entity.Property(e => e.FarmerId).HasColumnName("farmer_id");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("processing")
                .HasColumnName("status");

            entity.HasOne(d => d.Farmer).WithMany(p => p.ProcessingBatches)
                .HasForeignKey(d => d.FarmerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Processin__farme__4AB81AF0");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Roles__760965CCAFE588C2");

            entity.HasIndex(e => e.Name, "UQ__Roles__72E12F1B6A456088").IsUnique();

            entity.Property(e => e.RoleId)
                .ValueGeneratedNever()
                .HasColumnName("role_id");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__B9BE370F96EB7EEE");

            entity.HasIndex(e => e.Email, "UQ__Users__AB6E61648F579109").IsUnique();

            entity.HasIndex(e => e.Username, "UQ__Users__F3DBC57288E1FB1C").IsUnique();

            entity.Property(e => e.UserId)
                .ValueGeneratedNever()
                .HasColumnName("user_id");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.EmailVerified)
                .HasDefaultValue(false)
                .HasColumnName("email_verified");
            entity.Property(e => e.LastLoginAt)
                .HasColumnType("datetime")
                .HasColumnName("last_login_at");
            entity.Property(e => e.LoginType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("local")
                .HasColumnName("login_type");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("password_hash");
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("phone_number");
            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("active")
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("username");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Users__role_id__3D5E1FD2");
        });

        modelBuilder.Entity<Warehouse>(entity =>
        {
            entity.HasKey(e => e.WarehouseId).HasName("PK__Warehous__734FE6BF9F74A55A");

            entity.Property(e => e.WarehouseId)
                .ValueGeneratedNever()
                .HasColumnName("warehouse_id");
            entity.Property(e => e.Capacity).HasColumnName("capacity");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Location)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("location");
            entity.Property(e => e.ManagerId).HasColumnName("manager_id");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Manager).WithMany(p => p.Warehouses)
                .HasForeignKey(d => d.ManagerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Warehouse__manag__4E88ABD4");
        });

        modelBuilder.Entity<WarehouseInboundRequest>(entity =>
        {
            entity.HasKey(e => e.InboundRequestId).HasName("PK__Warehous__1B4E4CD0A86867A3");

            entity.Property(e => e.InboundRequestId)
                .ValueGeneratedNever()
                .HasColumnName("inbound_request_id");
            entity.Property(e => e.ActualDeliveryDate).HasColumnName("actual_delivery_date");
            entity.Property(e => e.BatchId).HasColumnName("batch_id");
            entity.Property(e => e.BusinessManagerId).HasColumnName("business_manager_id");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.FarmerId).HasColumnName("farmer_id");
            entity.Property(e => e.Note)
                .HasColumnType("text")
                .HasColumnName("note");
            entity.Property(e => e.PreferredDeliveryDate).HasColumnName("preferred_delivery_date");
            entity.Property(e => e.RequestedQuantity).HasColumnName("requested_quantity");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("pending")
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Batch).WithMany(p => p.WarehouseInboundRequests)
                .HasForeignKey(d => d.BatchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Warehouse__batch__5165187F");

            entity.HasOne(d => d.BusinessManager).WithMany(p => p.WarehouseInboundRequests)
                .HasForeignKey(d => d.BusinessManagerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Warehouse__busin__534D60F1");

            entity.HasOne(d => d.Farmer).WithMany(p => p.WarehouseInboundRequests)
                .HasForeignKey(d => d.FarmerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Warehouse__farme__52593CB8");
        });

        modelBuilder.Entity<WarehouseOutboundReceipt>(entity =>
        {
            entity.HasKey(e => e.ReceiptId).HasName("PK__Warehous__91F52C1F03291BB8");

            entity.Property(e => e.ReceiptId)
                .ValueGeneratedNever()
                .HasColumnName("receipt_id");
            entity.Property(e => e.BatchId).HasColumnName("batch_id");
            entity.Property(e => e.DeliveryNote)
                .HasColumnType("text")
                .HasColumnName("delivery_note");
            entity.Property(e => e.InventoryId).HasColumnName("inventory_id");
            entity.Property(e => e.IssuedAt)
                .HasColumnType("datetime")
                .HasColumnName("issued_at");
            entity.Property(e => e.IssuedBy).HasColumnName("issued_by");
            entity.Property(e => e.IssuedQuantity).HasColumnName("issued_quantity");
            entity.Property(e => e.QrCodeUrl)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("qr_code_url");
            entity.Property(e => e.RecipientName)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("recipient_name");
            entity.Property(e => e.WarehouseId).HasColumnName("warehouse_id");

            entity.HasOne(d => d.Batch).WithMany(p => p.WarehouseOutboundReceipts)
                .HasForeignKey(d => d.BatchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Warehouse__batch__71D1E811");

            entity.HasOne(d => d.Inventory).WithMany(p => p.WarehouseOutboundReceipts)
                .HasForeignKey(d => d.InventoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Warehouse__inven__72C60C4A");

            entity.HasOne(d => d.IssuedByNavigation).WithMany(p => p.WarehouseOutboundReceipts)
                .HasForeignKey(d => d.IssuedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Warehouse__issue__73BA3083");

            entity.HasOne(d => d.Warehouse).WithMany(p => p.WarehouseOutboundReceipts)
                .HasForeignKey(d => d.WarehouseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Warehouse__wareh__70DDC3D8");
        });

        modelBuilder.Entity<WarehouseOutboundRequest>(entity =>
        {
            entity.HasKey(e => e.OutboundRequestId).HasName("PK__Warehous__9DF89EC77815E78D");

            entity.Property(e => e.OutboundRequestId)
                .ValueGeneratedNever()
                .HasColumnName("outbound_request_id");
            entity.Property(e => e.ApprovedAt)
                .HasColumnType("datetime")
                .HasColumnName("approved_at");
            entity.Property(e => e.ApprovedBy).HasColumnName("approved_by");
            entity.Property(e => e.InventoryId).HasColumnName("inventory_id");
            entity.Property(e => e.Note)
                .HasColumnType("text")
                .HasColumnName("note");
            entity.Property(e => e.RequestedAt)
                .HasColumnType("datetime")
                .HasColumnName("requested_at");
            entity.Property(e => e.RequestedQuantity).HasColumnName("requested_quantity");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("pending")
                .HasColumnName("status");
            entity.Property(e => e.TraderId).HasColumnName("trader_id");

            entity.HasOne(d => d.ApprovedByNavigation).WithMany(p => p.WarehouseOutboundRequests)
                .HasForeignKey(d => d.ApprovedBy)
                .HasConstraintName("FK__Warehouse__appro__6E01572D");

            entity.HasOne(d => d.Inventory).WithMany(p => p.WarehouseOutboundRequests)
                .HasForeignKey(d => d.InventoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Warehouse__inven__6B24EA82");
        });

        modelBuilder.Entity<WarehouseReceipt>(entity =>
        {
            entity.HasKey(e => e.ReceiptId).HasName("PK__Warehous__91F52C1F0DD27ED0");

            entity.Property(e => e.ReceiptId)
                .ValueGeneratedNever()
                .HasColumnName("receipt_id");
            entity.Property(e => e.BatchId).HasColumnName("batch_id");
            entity.Property(e => e.InboundRequestId).HasColumnName("inbound_request_id");
            entity.Property(e => e.LotCode)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("lot_code");
            entity.Property(e => e.Note)
                .HasColumnType("text")
                .HasColumnName("note");
            entity.Property(e => e.QrCodeUrl)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("qr_code_url");
            entity.Property(e => e.ReceivedAt)
                .HasColumnType("datetime")
                .HasColumnName("received_at");
            entity.Property(e => e.ReceivedBy).HasColumnName("received_by");
            entity.Property(e => e.ReceivedQuantity).HasColumnName("received_quantity");
            entity.Property(e => e.WarehouseId).HasColumnName("warehouse_id");

            entity.HasOne(d => d.Batch).WithMany(p => p.WarehouseReceipts)
                .HasForeignKey(d => d.BatchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Warehouse__batch__59063A47");

            entity.HasOne(d => d.InboundRequest).WithMany(p => p.WarehouseReceipts)
                .HasForeignKey(d => d.InboundRequestId)
                .HasConstraintName("FK__Warehouse__inbou__571DF1D5");

            entity.HasOne(d => d.ReceivedByNavigation).WithMany(p => p.WarehouseReceipts)
                .HasForeignKey(d => d.ReceivedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Warehouse__recei__59FA5E80");

            entity.HasOne(d => d.Warehouse).WithMany(p => p.WarehouseReceipts)
                .HasForeignKey(d => d.WarehouseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Warehouse__wareh__5812160E");
        });

        modelBuilder.Entity<YieldAllocation>(entity =>
        {
            entity.HasKey(e => e.AllocationId).HasName("PK__YieldAll__5DFAFF30D84E866A");

            entity.Property(e => e.AllocationId)
                .ValueGeneratedNever()
                .HasColumnName("allocation_id");
            entity.Property(e => e.AllocatedAt)
                .HasColumnType("datetime")
                .HasColumnName("allocated_at");
            entity.Property(e => e.AllocatedBy).HasColumnName("allocated_by");
            entity.Property(e => e.AllocatedQuantity).HasColumnName("allocated_quantity");
            entity.Property(e => e.BatchId).HasColumnName("batch_id");
            entity.Property(e => e.InventoryId).HasColumnName("inventory_id");
            entity.Property(e => e.Note)
                .HasColumnType("text")
                .HasColumnName("note");
            entity.Property(e => e.ReceiptId).HasColumnName("receipt_id");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("active")
                .HasColumnName("status");

            entity.HasOne(d => d.AllocatedByNavigation).WithMany(p => p.YieldAllocations)
                .HasForeignKey(d => d.AllocatedBy)
                .HasConstraintName("FK__YieldAllo__alloc__6754599E");

            entity.HasOne(d => d.Batch).WithMany(p => p.YieldAllocations)
                .HasForeignKey(d => d.BatchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__YieldAllo__batch__656C112C");

            entity.HasOne(d => d.Inventory).WithMany(p => p.YieldAllocations)
                .HasForeignKey(d => d.InventoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__YieldAllo__inven__6477ECF3");

            entity.HasOne(d => d.Receipt).WithMany(p => p.YieldAllocations)
                .HasForeignKey(d => d.ReceiptId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__YieldAllo__recei__66603565");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}