// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoffeeManagement.Flow4.Repositories.Models;

public partial class Farmer
{
    public Guid UserId { get; set; }

    public string FullName { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string FarmLocation { get; set; }

    public double? FarmSize { get; set; }

    public string CertificationStatus { get; set; }

    public virtual ICollection<ProcessingBatch> ProcessingBatches { get; set; } = new List<ProcessingBatch>();

    public virtual User User { get; set; }

    public virtual ICollection<WarehouseInboundRequest> WarehouseInboundRequests { get; set; } = new List<WarehouseInboundRequest>();
}