// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoffeeManagement.Flow4.Repositories.Models;

public partial class Inventory
{
    public Guid InventoryId { get; set; }

    public Guid WarehouseId { get; set; }

    public Guid BatchId { get; set; }

    public double? Quantity { get; set; }

    public string Unit { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ProcessingBatch Batch { get; set; }

    public virtual ICollection<InventoryLog> InventoryLogs { get; set; } = new List<InventoryLog>();

    public virtual Warehouse Warehouse { get; set; }

    public virtual ICollection<WarehouseOutboundReceipt> WarehouseOutboundReceipts { get; set; } = new List<WarehouseOutboundReceipt>();

    public virtual ICollection<WarehouseOutboundRequest> WarehouseOutboundRequests { get; set; } = new List<WarehouseOutboundRequest>();

    public virtual ICollection<YieldAllocation> YieldAllocations { get; set; } = new List<YieldAllocation>();
}