// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoffeeManagement.Flow4.Repositories.Models;

public partial class ProcessingBatch
{
    public Guid BatchId { get; set; }

    public Guid? CropSeasonId { get; set; }

    public Guid FarmerId { get; set; }

    public string BatchCode { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string Status { get; set; }

    public virtual Farmer Farmer { get; set; }

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    public virtual ICollection<WarehouseInboundRequest> WarehouseInboundRequests { get; set; } = new List<WarehouseInboundRequest>();

    public virtual ICollection<WarehouseOutboundReceipt> WarehouseOutboundReceipts { get; set; } = new List<WarehouseOutboundReceipt>();

    public virtual ICollection<WarehouseReceipt> WarehouseReceipts { get; set; } = new List<WarehouseReceipt>();

    public virtual ICollection<YieldAllocation> YieldAllocations { get; set; } = new List<YieldAllocation>();
}