// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoffeeManagement.Flow4.Repositories.Models;

public partial class User
{
    public Guid UserId { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public bool? EmailVerified { get; set; }

    public string PasswordHash { get; set; }

    public string PhoneNumber { get; set; }

    public int RoleId { get; set; }

    public string LoginType { get; set; }

    public string Status { get; set; }

    public DateTime? LastLoginAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual BusinessManager BusinessManager { get; set; }

    public virtual Farmer Farmer { get; set; }

    public virtual Role Role { get; set; }
}