// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoffeeManagement.Flow4.Repositories.Models;

public partial class WarehouseReceipt
{
    public Guid ReceiptId { get; set; }

    public Guid? InboundRequestId { get; set; }

    public Guid WarehouseId { get; set; }

    public Guid BatchId { get; set; }

    public Guid ReceivedBy { get; set; }

    public string LotCode { get; set; }

    public double? ReceivedQuantity { get; set; }

    public DateTime? ReceivedAt { get; set; }

    public string Note { get; set; }

    public string QrCodeUrl { get; set; }

    public virtual ProcessingBatch Batch { get; set; }

    public virtual WarehouseInboundRequest InboundRequest { get; set; }

    public virtual BusinessManager ReceivedByNavigation { get; set; }

    public virtual Warehouse Warehouse { get; set; }

    public virtual ICollection<YieldAllocation> YieldAllocations { get; set; } = new List<YieldAllocation>();
}