// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoffeeManagement.Flow4.Repositories.Models;

public partial class WarehouseOutboundRequest
{
    public Guid OutboundRequestId { get; set; }

    public Guid InventoryId { get; set; }

    public Guid TraderId { get; set; }

    public double? RequestedQuantity { get; set; }

    public DateTime? RequestedAt { get; set; }

    public string Status { get; set; }

    public Guid? ApprovedBy { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public string Note { get; set; }

    public virtual BusinessManager ApprovedByNavigation { get; set; }

    public virtual Inventory Inventory { get; set; }
}