// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoffeeManagement.Flow4.Repositories.Models;

public partial class WarehouseOutboundReceipt
{
    public Guid ReceiptId { get; set; }

    public Guid WarehouseId { get; set; }

    public Guid BatchId { get; set; }

    public Guid InventoryId { get; set; }

    public Guid IssuedBy { get; set; }

    public double IssuedQuantity { get; set; }

    public DateTime IssuedAt { get; set; }

    public string RecipientName { get; set; }

    public string DeliveryNote { get; set; }

    public string QrCodeUrl { get; set; }

    public virtual ProcessingBatch Batch { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual BusinessManager IssuedByNavigation { get; set; }

    public virtual Warehouse Warehouse { get; set; }
}