// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoffeeManagement.Flow4.Repositories.Models;

public partial class YieldAllocation
{
    public Guid AllocationId { get; set; }

    public Guid InventoryId { get; set; }

    public Guid BatchId { get; set; }

    public Guid ReceiptId { get; set; }

    public double? AllocatedQuantity { get; set; }

    public DateTime? AllocatedAt { get; set; }

    public Guid? AllocatedBy { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public virtual BusinessManager AllocatedByNavigation { get; set; }

    public virtual ProcessingBatch Batch { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual WarehouseReceipt Receipt { get; set; }
}