// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class AgriculturalExpert
{
    [Key]
    public Guid ExpertId { get; set; }

    public string ExpertCode { get; set; }

    public Guid UserId { get; set; }

    public string ExpertiseArea { get; set; }

    public string Qualifications { get; set; }

    public int? YearsOfExperience { get; set; }

    public string AffiliatedOrganization { get; set; }

    public string Bio { get; set; }

    public double? Rating { get; set; }

    public bool? IsVerified { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<ExpertAdvice> ExpertAdvices { get; set; } = new List<ExpertAdvice>();

    public virtual UserAccount User { get; set; }
}