// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class BusinessBuyer
{
    public Guid BuyerId { get; set; }

    public string BuyerCode { get; set; }

    public Guid CreatedBy { get; set; }

    public string CompanyName { get; set; }

    public string ContactPerson { get; set; }

    public string Position { get; set; }

    public string CompanyAddress { get; set; }

    public string TaxId { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Website { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<Contract> Contracts { get; set; } = new List<Contract>();

    public virtual BusinessManager CreatedByNavigation { get; set; }

    public virtual ICollection<OrderComplaint> OrderComplaints { get; set; } = new List<OrderComplaint>();
}