// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class CoffeeType
{
    public Guid CoffeeTypeId { get; set; }

    public string TypeCode { get; set; }

    public string TypeName { get; set; }

    public string BotanicalName { get; set; }

    public string Description { get; set; }

    public string TypicalRegion { get; set; }

    public string SpecialtyLevel { get; set; }

    public double? DefaultYieldPerHectare { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<ContractItem> ContractItems { get; set; } = new List<ContractItem>();

    public virtual ICollection<ProcessingBatch> ProcessingBatches { get; set; } = new List<ProcessingBatch>();

    public virtual ICollection<ProcurementPlansDetail> ProcurementPlansDetails { get; set; } = new List<ProcurementPlansDetail>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}