// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class CommitmentViolation
{
    public Guid ViolationId { get; set; }

    public Guid CommitmentId { get; set; }

    public Guid ViolatorId { get; set; }

    public string ViolatorType { get; set; }

    public string ViolationType { get; set; }

    public string Description { get; set; }

    public string PenaltyAction { get; set; }

    public DateTime? ReportedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual FarmingCommitment Commitment { get; set; }

    public virtual UserAccount Violator { get; set; }
}