// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class CommitmentTemplate
{
    public Guid TemplateId { get; set; }

    public Guid BusinessId { get; set; }

    public string TemplateName { get; set; }

    public string DefaultQualityTerms { get; set; }

    public string DefaultPaymentTerms { get; set; }

    public string DefaultPenaltyTerms { get; set; }

    public string OtherTerms { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual BusinessManager Business { get; set; }

    public virtual ICollection<FarmingCommitment> FarmingCommitments { get; set; } = new List<FarmingCommitment>();
}