// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class CommitmentPayment
{
    public Guid PaymentId { get; set; }

    public Guid CommitmentId { get; set; }

    public string Cpcode { get; set; }

    public string PaymentStage { get; set; }

    public decimal Amount { get; set; }

    public DateOnly? DueDate { get; set; }

    public DateOnly? PaidDate { get; set; }

    public string Status { get; set; }

    public string PaymentMethod { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual FarmingCommitment Commitment { get; set; }
}