// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class ContractDeliveryItem
{
    public Guid DeliveryItemId { get; set; }

    public string DeliveryItemCode { get; set; }

    public Guid DeliveryBatchId { get; set; }

    public Guid ContractItemId { get; set; }

    public double PlannedQuantity { get; set; }

    public double? FulfilledQuantity { get; set; }

    public string Note { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ContractItem ContractItem { get; set; }

    public virtual ContractDeliveryBatch DeliveryBatch { get; set; }

    public virtual ICollection<FarmingCommitment> FarmingCommitments { get; set; } = new List<FarmingCommitment>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}