// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class ContractDeliveryBatch
{
    public Guid DeliveryBatchId { get; set; }

    public string DeliveryBatchCode { get; set; }

    public Guid ContractId { get; set; }

    public int DeliveryRound { get; set; }

    public DateOnly? ExpectedDeliveryDate { get; set; }

    public double? TotalPlannedQuantity { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual Contract Contract { get; set; }

    public virtual ICollection<ContractDeliveryItem> ContractDeliveryItems { get; set; } = new List<ContractDeliveryItem>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}