// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class ContractItem
{
    public Guid ContractItemId { get; set; }

    public string ContractItemCode { get; set; }

    public Guid ContractId { get; set; }

    public Guid CoffeeTypeId { get; set; }

    public double? Quantity { get; set; }

    public double? UnitPrice { get; set; }

    public double? DiscountAmount { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual CoffeeType CoffeeType { get; set; }

    public virtual Contract Contract { get; set; }

    public virtual ICollection<ContractDeliveryItem> ContractDeliveryItems { get; set; } = new List<ContractDeliveryItem>();

    public virtual ICollection<ProcurementPlansDetail> ProcurementPlansDetails { get; set; } = new List<ProcurementPlansDetail>();
}