// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class Conversation
{
    public Guid ConversationId { get; set; }

    public string Topic { get; set; }

    public Guid? CropProgressId { get; set; }

    public Guid? BatchId { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ProcessingBatch Batch { get; set; }

    public virtual ICollection<ConversationMessage> ConversationMessages { get; set; } = new List<ConversationMessage>();

    public virtual ICollection<ConversationParticipant> ConversationParticipants { get; set; } = new List<ConversationParticipant>();

    public virtual UserAccount CreatedByNavigation { get; set; }

    public virtual CropProgress CropProgress { get; set; }
}