// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class CropSeasonDetail
{
    [Key]
    public Guid DetailId { get; set; }

    public Guid CropSeasonId { get; set; }

    public Guid CommitmentDetailId { get; set; }

    public DateOnly? ExpectedHarvestStart { get; set; }

    public DateOnly? ExpectedHarvestEnd { get; set; }

    public double? EstimatedYield { get; set; }

    public double? ActualYield { get; set; }

    public double? AreaAllocated { get; set; }

    public string PlannedQuality { get; set; }

    public string QualityGrade { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual FarmingCommitmentsDetail CommitmentDetail { get; set; }

    public virtual ICollection<CropProgress> CropProgresses { get; set; } = new List<CropProgress>();

    public virtual CropSeason CropSeason { get; set; }

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    public virtual ICollection<WarehouseInboundRequest> WarehouseInboundRequests { get; set; } = new List<WarehouseInboundRequest>();

    public virtual ICollection<WarehouseReceipt> WarehouseReceipts { get; set; } = new List<WarehouseReceipt>();
}