// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class CropProgress
{
    [Key]
    public Guid ProgressId { get; set; }

    public Guid CropSeasonDetailId { get; set; }

    public Guid UpdatedBy { get; set; }

    public int StageId { get; set; }

    public string StageDescription { get; set; }

    public DateOnly? ProgressDate { get; set; }

    public string PhotoUrl { get; set; }

    public string VideoUrl { get; set; }

    public string Note { get; set; }

    public int? StepIndex { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual CropSeasonDetail CropSeasonDetail { get; set; }

    public virtual ICollection<GeneralFarmerReport> GeneralFarmerReports { get; set; } = new List<GeneralFarmerReport>();

    public virtual CropStage Stage { get; set; }

    public virtual Farmer UpdatedByNavigation { get; set; }

}