// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class CropStage
{
    public int StageId { get; set; }

    public string StageCode { get; set; }

    public string StageName { get; set; }

    public string Description { get; set; }

    public int? OrderIndex { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<CropProgress> CropProgresses { get; set; } = new List<CropProgress>();
}