// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class CultivationRegistrationsDetail
{
    [Key]
    public Guid CultivationRegistrationDetailId { get; set; }

    public Guid RegistrationId { get; set; }

    public Guid PlanDetailId { get; set; }

    public double? EstimatedYield { get; set; }

    public DateOnly? ExpectedHarvestStart { get; set; }

    public DateOnly? ExpectedHarvestEnd { get; set; }

    public double? WantedPrice { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public string SystemNote { get; set; }

    public Guid? ApprovedBy { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual BusinessManager ApprovedByNavigation { get; set; }

    public virtual ICollection<FarmingCommitmentsDetail> FarmingCommitmentsDetails { get; set; } = new List<FarmingCommitmentsDetail>();

    public virtual ProcurementPlansDetail PlanDetail { get; set; }

    public virtual CultivationRegistration Registration { get; set; }
}