// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class CultivationRegistration
{
    public Guid RegistrationId { get; set; }

    public string RegistrationCode { get; set; }

    public Guid PlanId { get; set; }

    public Guid FarmerId { get; set; }

    public double? RegisteredArea { get; set; }

    public DateTime RegisteredAt { get; set; }

    public double? WantedPrice { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public string SystemNote { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<CropSeason> CropSeasons { get; set; } = new List<CropSeason>();

    public virtual ICollection<CultivationRegistrationsDetail> CultivationRegistrationsDetails { get; set; } = new List<CultivationRegistrationsDetail>();

    public virtual Farmer Farmer { get; set; }

    public virtual ProcurementPlan Plan { get; set; }
}