// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class ExpertAdvice
{
    public Guid AdviceId { get; set; }

    public Guid ReportId { get; set; }

    public Guid ExpertId { get; set; }

    public string ResponseType { get; set; }

    public string AdviceSource { get; set; }

    public string AdviceText { get; set; }

    public string AttachedFileUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual AgriculturalExpert Expert { get; set; }

    public virtual GeneralFarmerReport Report { get; set; }
}