// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class Farmer
{
    [Key]
    public Guid FarmerId { get; set; }

    public string FarmerCode { get; set; }

    public Guid UserId { get; set; }

    public string FarmLocation { get; set; }

    public double? FarmSize { get; set; }

    public string CertificationStatus { get; set; }

    public string CertificationUrl { get; set; }

    public bool? IsVerified { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<CropProgress> CropProgresses { get; set; } = new List<CropProgress>();

    public virtual ICollection<CropSeason> CropSeasons { get; set; } = new List<CropSeason>();

    public virtual ICollection<CultivationRegistration> CultivationRegistrations { get; set; } = new List<CultivationRegistration>();

    public virtual ICollection<FarmingCommitment> FarmingCommitments { get; set; } = new List<FarmingCommitment>();

    public virtual ICollection<ProcessingBatchProgress> ProcessingBatchProgresses { get; set; } = new List<ProcessingBatchProgress>();

    public virtual ICollection<ProcessingBatch> ProcessingBatches { get; set; } = new List<ProcessingBatch>();

    public virtual UserAccount User { get; set; }

    public virtual ICollection<WarehouseInboundRequest> WarehouseInboundRequests { get; set; } = new List<WarehouseInboundRequest>();
}