// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class FarmingCommitment
{
    public Guid CommitmentId { get; set; }

    public string CommitmentCode { get; set; }

    public Guid RegistrationDetailId { get; set; }

    public Guid PlanDetailId { get; set; }

    public Guid FarmerId { get; set; }

    public double? ConfirmedPrice { get; set; }

    public double? CommittedQuantity { get; set; }

    public DateOnly? EstimatedDeliveryStart { get; set; }

    public DateOnly? EstimatedDeliveryEnd { get; set; }

    public DateTime CommitmentDate { get; set; }

    public Guid? ApprovedBy { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public string Status { get; set; }

    public string RejectionReason { get; set; }

    public string Note { get; set; }

    public Guid? ContractDeliveryItemId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual BusinessManager ApprovedByNavigation { get; set; }

    public virtual ContractDeliveryItem ContractDeliveryItem { get; set; }

    public virtual ICollection<CropSeason> CropSeasons { get; set; } = new List<CropSeason>();

    public virtual Farmer Farmer { get; set; }

    public virtual ProcurementPlansDetail PlanDetail { get; set; }

    public virtual CultivationRegistrationsDetail RegistrationDetail { get; set; }
}