// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class FarmingCommitment
{
    [Key]
    public Guid CommitmentId { get; set; }

    public string CommitmentCode { get; set; }

    public string CommitmentName { get; set; }

    public Guid PlanId { get; set; }

    public Guid RegistrationId { get; set; }

    public Guid FarmerId { get; set; }

    public double? TotalPrice { get; set; }

    public double? TotalAdvancePayment { get; set; }

    public double? TotalTaxPrice { get; set; }

    public DateTime CommitmentDate { get; set; }

    public Guid? ApprovedBy { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public string Status { get; set; }

    public double? ProgressPercentage { get; set; }

    public string RejectionReason { get; set; }

    public string Note { get; set; }

    public double? TotalRatingByBusiness { get; set; }

    public double? TotalRatingByFarmer { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual BusinessManager ApprovedByNavigation { get; set; }

    public virtual ICollection<CropSeason> CropSeasons { get; set; } = new List<CropSeason>();

    public virtual Farmer Farmer { get; set; }

    public virtual ICollection<FarmingCommitmentsDetail> FarmingCommitmentsDetails { get; set; } = new List<FarmingCommitmentsDetail>();

    public virtual ProcurementPlan Plan { get; set; }

    public virtual CultivationRegistration Registration { get; set; }
}