// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class FarmingCommitment
{
    public Guid CommitmentId { get; set; }

    public string CommitmentCode { get; set; }

    public string CommitmentName { get; set; }

    public Guid PlanId { get; set; }

    public Guid RegistrationId { get; set; }

    public Guid FarmerId { get; set; }

    public DateTime CommitmentDate { get; set; }

    public Guid? ApprovedBy { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public string Status { get; set; }

    public string RejectionReason { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual BusinessManager ApprovedByNavigation { get; set; }

    public virtual CropSeason CropSeason { get; set; }

    public virtual Farmer Farmer { get; set; }

    public virtual ProcurementPlan Plan { get; set; }

    public virtual CultivationRegistration Registration { get; set; }
}