// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class GeneralFarmerReport
{
    public Guid ReportId { get; set; }

    public string ReportCode { get; set; }

    public string ReportType { get; set; }

    public Guid? CropProgressId { get; set; }

    public Guid? ProcessingProgressId { get; set; }

    public Guid ReportedBy { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int? SeverityLevel { get; set; }

    public string ImageUrl { get; set; }

    public string VideoUrl { get; set; }

    public bool? IsResolved { get; set; }

    public DateTime ReportedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime? ResolvedAt { get; set; }

    public virtual CropProgress CropProgress { get; set; }

    public virtual ICollection<ExpertAdvice> ExpertAdvices { get; set; } = new List<ExpertAdvice>();

    public virtual ProcessingBatchProgress ProcessingProgress { get; set; }

    public virtual UserAccount ReportedByNavigation { get; set; }
}