// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class Inventory
{
    public Guid InventoryId { get; set; }

    public string InventoryCode { get; set; }

    public Guid WarehouseId { get; set; }

    public Guid BatchId { get; set; }

    public double Quantity { get; set; }

    public string Unit { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ProcessingBatch Batch { get; set; }

    public virtual ICollection<InventoryLog> InventoryLogs { get; set; } = new List<InventoryLog>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual Warehouse Warehouse { get; set; }

    public virtual ICollection<WarehouseOutboundReceipt> WarehouseOutboundReceipts { get; set; } = new List<WarehouseOutboundReceipt>();

    public virtual ICollection<WarehouseOutboundRequest> WarehouseOutboundRequests { get; set; } = new List<WarehouseOutboundRequest>();
}