// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class InventoryLog
{
    public Guid LogId { get; set; }

    public Guid InventoryId { get; set; }

    public string ActionType { get; set; }

    public double QuantityChanged { get; set; }

    public Guid? UpdatedBy { get; set; }

    public bool? TriggeredBySystem { get; set; }

    public string Note { get; set; }

    public DateTime LoggedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual Inventory Inventory { get; set; }
}