// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class ManualViolation
{
    public Guid ReportId { get; set; }

    public Guid CommitmentId { get; set; }

    public Guid ReporterId { get; set; }

    public string ReporterType { get; set; }

    public string TargetType { get; set; }

    public Guid TargetId { get; set; }

    public string ViolationType { get; set; }

    public string Description { get; set; }

    public string EvidenceLinks { get; set; }

    public string Status { get; set; }

    public Guid? ApprovedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual UserAccount ApprovedByNavigation { get; set; }

    public virtual FarmingCommitment Commitment { get; set; }
}