// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class MediaFile
{
    public Guid MediaId { get; set; }

    public string RelatedEntity { get; set; }

    public Guid RelatedId { get; set; }

    public string MediaType { get; set; }

    public string MediaUrl { get; set; }

    public string Caption { get; set; }

    public DateTime UploadedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }
}