// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class OrderComplaint
{
    public Guid ComplaintId { get; set; }

    public string ComplaintCode { get; set; }

    public Guid OrderItemId { get; set; }

    public Guid RaisedBy { get; set; }

    public string ComplaintType { get; set; }

    public string Description { get; set; }

    public string EvidenceUrl { get; set; }

    public string Status { get; set; }

    public string ResolutionNote { get; set; }

    public Guid? ResolvedBy { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime? ResolvedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual UserAccount CreatedByNavigation { get; set; }

    public virtual OrderItem OrderItem { get; set; }

    public virtual BusinessBuyer RaisedByNavigation { get; set; }

    public virtual BusinessManager ResolvedByNavigation { get; set; }
}