// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class Order
{
    public Guid OrderId { get; set; }

    public string OrderCode { get; set; }

    public Guid DeliveryBatchId { get; set; }

    public int? DeliveryRound { get; set; }

    public DateTime? OrderDate { get; set; }

    public DateOnly? ActualDeliveryDate { get; set; }

    public double? TotalAmount { get; set; }

    public string Note { get; set; }

    public string Status { get; set; }

    public string CancelReason { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ContractDeliveryBatch DeliveryBatch { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<Shipment> Shipments { get; set; } = new List<Shipment>();
}