// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class Order
{
    public Guid OrderId { get; set; }

    public string OrderCode { get; set; }

    public Guid ContractId { get; set; }

    public Guid BuyerId { get; set; }

    public Guid SellerId { get; set; }

    public int? DeliveryRound { get; set; }

    public DateTime? OrderDate { get; set; }

    public DateOnly? ExpectedDeliveryDate { get; set; }

    public DateOnly? ActualDeliveryDate { get; set; }

    public double? TotalAmount { get; set; }

    public string Note { get; set; }

    public string Status { get; set; }

    public string CancelReason { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual BusinessBuyer Buyer { get; set; }

    public virtual Contract Contract { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual BusinessManager Seller { get; set; }

    public virtual ICollection<Shipment> Shipments { get; set; } = new List<Shipment>();
}