// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class OrderItem
{
    public Guid OrderItemId { get; set; }

    public Guid OrderId { get; set; }

    public Guid ProductId { get; set; }

    public double? Quantity { get; set; }

    public double? UnitPrice { get; set; }

    public double? DiscountAmount { get; set; }

    public double? TotalPrice { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<OrderComplaint> OrderComplaints { get; set; } = new List<OrderComplaint>();

    public virtual Product Product { get; set; }

    public virtual ICollection<WarehouseOutboundRequest> WarehouseOutboundRequests { get; set; } = new List<WarehouseOutboundRequest>();
}