// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class PaymentConfiguration
{
    [Key]
    public Guid ConfigId { get; set; }

    public int RoleId { get; set; }

    public string FeeType { get; set; }

    public double Amount { get; set; }

    public string ConfigName { get; set; }

    public double? MinTons { get; set; }

    public double? MaxTons { get; set; }

    public string Description { get; set; }

    public DateOnly EffectiveFrom { get; set; }

    public DateOnly? EffectiveTo { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool? IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Role Role { get; set; }
}