// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class Payment
{
    [Key]
    public Guid PaymentId { get; set; }

    public string Email { get; set; }

    public Guid ConfigId { get; set; }

    public Guid? UserId { get; set; }

    public string PaymentCode { get; set; }

    public double PaymentAmount { get; set; }

    public string PaymentMethod { get; set; }

    public string PaymentPurpose { get; set; }

    public string PaymentStatus { get; set; }

    public DateTime? PaymentTime { get; set; }

    public bool? AdminVerified { get; set; }

    public string RefundReason { get; set; }

    public DateTime? RefundTime { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public Guid? RelatedEntityId { get; set; }

    public bool IsDeleted { get; set; }

    public virtual PaymentConfiguration Config { get; set; }

    public virtual UserAccount User { get; set; }

    public virtual ICollection<WalletTransaction> WalletTransactions { get; set; } = new List<WalletTransaction>();
}