// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class ProcessingParameter
{
    [Key]
    public Guid ParameterId { get; set; }

    public Guid ProgressId { get; set; }

    public string ParameterName { get; set; }

    public string ParameterValue { get; set; }

    public string Unit { get; set; }

    public DateTime? RecordedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ProcessingBatchProgress Progress { get; set; }
}