// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class ProcessingBatchEvaluation
{
    public Guid EvaluationId { get; set; }

    public string EvaluationCode { get; set; }

    public Guid BatchId { get; set; }

    public Guid? EvaluatedBy { get; set; }

    public string EvaluationResult { get; set; }

    public string Comments { get; set; }

    public DateTime? EvaluatedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public decimal? TotalScore { get; set; }

    public string DecisionReason { get; set; }

    public string CriteriaSnapshot { get; set; }

    public virtual ProcessingBatch Batch { get; set; }
}