// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class ProcurementPlan
{
    [Key]
    public Guid PlanId { get; set; }

    public string PlanCode { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public double? TotalQuantity { get; set; }

    public Guid CreatedBy { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public string Status { get; set; }

    public double? ProgressPercentage { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual BusinessManager CreatedByNavigation { get; set; }

    public virtual ICollection<CultivationRegistration> CultivationRegistrations { get; set; } = new List<CultivationRegistration>();

    public virtual ICollection<FarmingCommitment> FarmingCommitments { get; set; } = new List<FarmingCommitment>();

    public virtual ICollection<ProcurementPlansDetail> ProcurementPlansDetails { get; set; } = new List<ProcurementPlansDetail>();
}