// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class ProcessingBatch
{
    [Key]
    public Guid BatchId { get; set; }

    public string SystemBatchCode { get; set; }

    public Guid CoffeeTypeId { get; set; }

    public Guid CropSeasonId { get; set; }

    public Guid FarmerId { get; set; }

    public string BatchCode { get; set; }

    public int MethodId { get; set; }

    public double InputQuantity { get; set; }

    public string InputUnit { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string Status { get; set; }

    public bool IsDeleted { get; set; }

    public virtual CoffeeType CoffeeType { get; set; }

    public virtual CropSeason CropSeason { get; set; }

    public virtual Farmer Farmer { get; set; }

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    public virtual ProcessingMethod Method { get; set; }

    public virtual ICollection<ProcessingBatchEvaluation> ProcessingBatchEvaluations { get; set; } = new List<ProcessingBatchEvaluation>();

    public virtual ICollection<ProcessingBatchProgress> ProcessingBatchProgresses { get; set; } = new List<ProcessingBatchProgress>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ICollection<WarehouseInboundRequest> WarehouseInboundRequests { get; set; } = new List<WarehouseInboundRequest>();

    public virtual ICollection<WarehouseOutboundReceipt> WarehouseOutboundReceipts { get; set; } = new List<WarehouseOutboundReceipt>();

    public virtual ICollection<WarehouseReceipt> WarehouseReceipts { get; set; } = new List<WarehouseReceipt>();
}