// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class ProcurementPlansDetail
{
    public Guid PlanDetailsId { get; set; }

    public string PlanDetailCode { get; set; }

    public Guid PlanId { get; set; }

    public Guid CoffeeTypeId { get; set; }

    public int ProcessMethodId { get; set; }

    public double? TargetQuantity { get; set; }

    public string TargetRegion { get; set; }

    public double? MinimumRegistrationQuantity { get; set; }

    public double? MinPriceRange { get; set; }

    public double? MaxPriceRange { get; set; }

    public double? ExpectedYieldPerHectare { get; set; }

    public string Note { get; set; }

    public double? ProgressPercentage { get; set; }

    public Guid? ContractItemId { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual CoffeeType CoffeeType { get; set; }

    public virtual ContractItem ContractItem { get; set; }

    public virtual ICollection<CultivationRegistrationsDetail> CultivationRegistrationsDetails { get; set; } = new List<CultivationRegistrationsDetail>();

    public virtual ICollection<FarmingCommitmentsDetail> FarmingCommitmentsDetails { get; set; } = new List<FarmingCommitmentsDetail>();

    public virtual ProcurementPlan Plan { get; set; }

    public virtual ProcessingMethod ProcessMethod { get; set; }
}