// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class ProcessingStage
{
    public int StageId { get; set; }

    public int MethodId { get; set; }

    public string StageCode { get; set; }

    public string StageName { get; set; }

    public string Description { get; set; }

    public int OrderIndex { get; set; }

    public bool? IsRequired { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ProcessingMethod Method { get; set; }

    public virtual ICollection<ProcessingBatchProgress> ProcessingBatchProgresses { get; set; } = new List<ProcessingBatchProgress>();
}