// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class ProcessingBatchWaste
{
    [Key]
    public Guid WasteId { get; set; }

    public string WasteCode { get; set; }

    public Guid ProgressId { get; set; }

    public string WasteType { get; set; }

    public double? Quantity { get; set; }

    public string Unit { get; set; }

    public string Note { get; set; }

    public DateTime? RecordedAt { get; set; }

    public Guid? RecordedBy { get; set; }

    public bool? IsDisposed { get; set; }

    public DateTime? DisposedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<ProcessingWasteDisposal> ProcessingWasteDisposals { get; set; } = new List<ProcessingWasteDisposal>();

    public virtual ProcessingBatchProgress Progress { get; set; }
}