// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class ProcurementPlansDetail
{
    public Guid PlanDetailsId { get; set; }

    public string PlanDetailCode { get; set; }

    public Guid PlanId { get; set; }

    public Guid CoffeeTypeId { get; set; }

    public string CropType { get; set; }

    public double? TargetQuantity { get; set; }

    public string TargetRegion { get; set; }

    public double? MinimumRegistrationQuantity { get; set; }

    public string BeanSize { get; set; }

    public string BeanColor { get; set; }

    public double? MoistureContent { get; set; }

    public double? DefectRate { get; set; }

    public double? MinPriceRange { get; set; }

    public double? MaxPriceRange { get; set; }

    public string Note { get; set; }

    public string BeanColorImageUrl { get; set; }

    public double? ProgressPercentage { get; set; }

    public Guid? ContractItemId { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual CoffeeType CoffeeType { get; set; }

    public virtual ContractItem ContractItem { get; set; }

    public virtual ICollection<CultivationRegistrationsDetail> CultivationRegistrationsDetails { get; set; } = new List<CultivationRegistrationsDetail>();

    public virtual ICollection<FarmingCommitment> FarmingCommitments { get; set; } = new List<FarmingCommitment>();

    public virtual ProcurementPlan Plan { get; set; }
}