// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class ProcessingBatchProgress
{
    [Key]
    public Guid ProgressId { get; set; }

    public Guid BatchId { get; set; }

    public int StepIndex { get; set; }

    public int StageId { get; set; }

    public string StageDescription { get; set; }

    public DateOnly? ProgressDate { get; set; }

    public double? OutputQuantity { get; set; }

    public string OutputUnit { get; set; }

    public Guid UpdatedBy { get; set; }

    public string PhotoUrl { get; set; }

    public string VideoUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ProcessingBatch Batch { get; set; }

    public virtual ICollection<GeneralFarmerReport> GeneralFarmerReports { get; set; } = new List<GeneralFarmerReport>();

    public virtual ICollection<ProcessingBatchWaste> ProcessingBatchWastes { get; set; } = new List<ProcessingBatchWaste>();

    public virtual ICollection<ProcessingParameter> ProcessingParameters { get; set; } = new List<ProcessingParameter>();

    public virtual ProcessingStage Stage { get; set; }

    public virtual Farmer UpdatedByNavigation { get; set; }
}