// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class Product
{
    [Key]
    public Guid ProductId { get; set; }

    public string ProductCode { get; set; }

    public string ProductName { get; set; }

    public string Description { get; set; }

    public double? UnitPrice { get; set; }

    public double? QuantityAvailable { get; set; }

    public string Unit { get; set; }

    public Guid CreatedBy { get; set; }

    public Guid BatchId { get; set; }

    public Guid InventoryId { get; set; }

    public Guid CoffeeTypeId { get; set; }

    public string OriginRegion { get; set; }

    public string OriginFarmLocation { get; set; }

    public string GeographicalIndicationCode { get; set; }

    public string CertificationUrl { get; set; }

    public string EvaluatedQuality { get; set; }

    public double? EvaluationScore { get; set; }

    public string Status { get; set; }

    public Guid? ApprovedBy { get; set; }

    public string ApprovalNote { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual UserAccount ApprovedByNavigation { get; set; }

    public virtual ProcessingBatch Batch { get; set; }

    public virtual CoffeeType CoffeeType { get; set; }

    public virtual BusinessManager CreatedByNavigation { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}