// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class ReputationHistory
{
    public Guid ReputationHistoryId { get; set; }

    public Guid CommitmentId { get; set; }

    public Guid UserId { get; set; }

    public string UserType { get; set; }

    public int? ScoreChange { get; set; }

    public int? NewScore { get; set; }

    public string Reason { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual FarmingCommitment Commitment { get; set; }

    public virtual UserAccount User { get; set; }
}