// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class Shipment
{
    public Guid ShipmentId { get; set; }

    public string ShipmentCode { get; set; }

    public Guid OrderId { get; set; }

    public Guid DeliveryStaffId { get; set; }

    public double? ShippedQuantity { get; set; }

    public DateTime? ShippedAt { get; set; }

    public string DeliveryStatus { get; set; }

    public DateTime? ReceivedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual UserAccount DeliveryStaff { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<ShipmentDetail> ShipmentDetails { get; set; } = new List<ShipmentDetail>();
}