// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class ShipmentDetail
{
    public Guid ShipmentDetailId { get; set; }

    public Guid ShipmentId { get; set; }

    public Guid ProductId { get; set; }

    public double? Quantity { get; set; }

    public string Unit { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Product Product { get; set; }

    public virtual Shipment Shipment { get; set; }
}