// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class SystemNotification
{
    public Guid NotificationId { get; set; }

    public string NotificationCode { get; set; }

    public string Title { get; set; }

    public string Message { get; set; }

    public string Type { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual UserAccount CreatedByNavigation { get; set; }

    public virtual ICollection<SystemNotificationRecipient> SystemNotificationRecipients { get; set; } = new List<SystemNotificationRecipient>();
}