// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class SystemConfigurationUser
{
    public int Id { get; set; }

    public int SystemConfigurationId { get; set; }

    public Guid UserId { get; set; }

    public string PermissionLevel { get; set; }

    public DateTime GrantedAt { get; set; }

    public DateTime? RevokedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual SystemConfiguration SystemConfiguration { get; set; }

    public virtual UserAccount User { get; set; }
}