// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class SystemNotificationRecipient
{
    public Guid Id { get; set; }

    public Guid NotificationId { get; set; }

    public Guid RecipientId { get; set; }

    public bool? IsRead { get; set; }

    public DateTime? ReadAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual SystemNotification Notification { get; set; }

    public virtual UserAccount Recipient { get; set; }
}