// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class TriggerRule
{
    public Guid RuleId { get; set; }

    public string RuleName { get; set; }

    public string TargetType { get; set; }

    public string TriggerEvent { get; set; }

    public string ConditionExpression { get; set; }

    public int PointChange { get; set; }

    public string ApplyOn { get; set; }

    public bool Enabled { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }
}