// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class UserAccount
{
    public Guid UserId { get; set; }

    public string UserCode { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Name { get; set; }

    public string Gender { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Address { get; set; }

    public byte[] ProfilePicture { get; set; }

    public string PasswordHash { get; set; }

    public DateTime RegistrationDate { get; set; }

    public DateTime? LastLogin { get; set; }

    public bool? EmailVerified { get; set; }

    public string VerificationCode { get; set; }

    public bool? IsVerified { get; set; }

    public string LoginType { get; set; }

    public string Status { get; set; }

    public int RoleId { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual AgriculturalExpert AgriculturalExpert { get; set; }

    public virtual ICollection<BusinessManager> BusinessManagers { get; set; } = new List<BusinessManager>();

    public virtual BusinessStaff BusinessStaff { get; set; }

    public virtual ICollection<ConversationMessage> ConversationMessages { get; set; } = new List<ConversationMessage>();

    public virtual ICollection<ConversationParticipant> ConversationParticipants { get; set; } = new List<ConversationParticipant>();

    public virtual ICollection<Conversation> Conversations { get; set; } = new List<Conversation>();

    public virtual ICollection<Farmer> Farmers { get; set; } = new List<Farmer>();

    public virtual ICollection<GeneralFarmerReport> GeneralFarmerReports { get; set; } = new List<GeneralFarmerReport>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual Role Role { get; set; }

    public virtual ICollection<Shipment> Shipments { get; set; } = new List<Shipment>();

    public virtual ICollection<SystemNotificationRecipient> SystemNotificationRecipients { get; set; } = new List<SystemNotificationRecipient>();

    public virtual ICollection<SystemNotification> SystemNotifications { get; set; } = new List<SystemNotification>();
}