// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class WarehouseInboundRequest
{
    public Guid InboundRequestId { get; set; }

    public string InboundRequestCode { get; set; }

    public Guid BatchId { get; set; }

    public Guid FarmerId { get; set; }

    public Guid BusinessStaffId { get; set; }

    public double? RequestedQuantity { get; set; }

    public DateOnly? PreferredDeliveryDate { get; set; }

    public DateOnly? ActualDeliveryDate { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ProcessingBatch Batch { get; set; }

    public virtual BusinessStaff BusinessStaff { get; set; }

    public virtual Farmer Farmer { get; set; }

    public virtual ICollection<WarehouseReceipt> WarehouseReceipts { get; set; } = new List<WarehouseReceipt>();
}