// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class WarehouseReceipt
{
    [Key]
    public Guid ReceiptId { get; set; }

    public string ReceiptCode { get; set; }

    public Guid InboundRequestId { get; set; }

    public Guid WarehouseId { get; set; }

    public Guid? BatchId { get; set; }

    public Guid? DetailId { get; set; }

    public Guid ReceivedBy { get; set; }

    public string LotCode { get; set; }

    public double? ReceivedQuantity { get; set; }

    public DateTime? ReceivedAt { get; set; }

    public string Note { get; set; }

    public string QrcodeUrl { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ProcessingBatch Batch { get; set; }

    public virtual CropSeasonDetail Detail { get; set; }

    public virtual WarehouseInboundRequest InboundRequest { get; set; }

    public virtual BusinessStaff ReceivedByNavigation { get; set; }

    public virtual Warehouse Warehouse { get; set; }
}