// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class Warehouse
{
    public Guid WarehouseId { get; set; }

    public string WarehouseCode { get; set; }

    public Guid ManagerId { get; set; }

    public string Name { get; set; }

    public string Location { get; set; }

    public double? Capacity { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<BusinessStaff> BusinessStaffs { get; set; } = new List<BusinessStaff>();

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    public virtual BusinessManager Manager { get; set; }

    public virtual ICollection<WarehouseOutboundReceipt> WarehouseOutboundReceipts { get; set; } = new List<WarehouseOutboundReceipt>();

    public virtual ICollection<WarehouseOutboundRequest> WarehouseOutboundRequests { get; set; } = new List<WarehouseOutboundRequest>();

    public virtual ICollection<WarehouseReceipt> WarehouseReceipts { get; set; } = new List<WarehouseReceipt>();
}