// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class WarehouseOutboundRequest
{
    public Guid OutboundRequestId { get; set; }

    public string OutboundRequestCode { get; set; }

    public Guid WarehouseId { get; set; }

    public Guid InventoryId { get; set; }

    public double RequestedQuantity { get; set; }

    public string Unit { get; set; }

    public Guid RequestedBy { get; set; }

    public string Purpose { get; set; }

    public Guid? OrderItemId { get; set; }

    public string Reason { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual OrderItem OrderItem { get; set; }

    public virtual BusinessStaff RequestedByNavigation { get; set; }

    public virtual Warehouse Warehouse { get; set; }

    public virtual ICollection<WarehouseOutboundReceipt> WarehouseOutboundReceipts { get; set; } = new List<WarehouseOutboundReceipt>();
}