// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DakLakCoffeeSupplyChain.Repositories.Models;

public partial class WarehouseInboundRequest
{
    [Key]
    public Guid InboundRequestId { get; set; }

    public string InboundRequestCode { get; set; }

    public Guid? BatchId { get; set; }

    public Guid? DetailId { get; set; }

    public Guid FarmerId { get; set; }

    public Guid? BusinessStaffId { get; set; }

    public double? RequestedQuantity { get; set; }

    public DateOnly? PreferredDeliveryDate { get; set; }

    public DateOnly? ActualDeliveryDate { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ProcessingBatch Batch { get; set; }

    public virtual BusinessStaff BusinessStaff { get; set; }

    public virtual CropSeasonDetail Detail { get; set; }

    public virtual Farmer Farmer { get; set; }

    public virtual ICollection<WarehouseReceipt> WarehouseReceipts { get; set; } = new List<WarehouseReceipt>();
}