name: auto-build-deploy
on:
  push:
    branches: ["main"]

jobs:
  build-check:
    runs-on: ubuntu-24.04
    steps:
      - name: checking allow to build
        run: |
          if [ "${{ secrets.BUILD }}" = "ACTIVE" ]; then
            echo '------------------- ready to deploy --------------------'
          else
            echo 'not ready'
            exit 1
          fi

  build-push:
    needs: build-check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Dùng cache GHA tích hợp của buildx (nhanh & gọn)
      - name: Build and Push for Server
        uses: docker/build-push-action@v6
        id: docker_build_server
        with:
          context: ./Source/DakLakCoffeeSupplyChainBE
          file: ./Source/DakLakCoffeeSupplyChainBE/Dockerfile
          push: true
          tags: tranthequang/daklak-coffee-scm:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify
        run: |
          echo "${{ steps.docker_build_server.outputs.digest }}"
          echo 'Build done, ready to deploy'

  deploy:
    needs: build-push
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy via SSH (pull & restart compose)
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          # Khuyên dùng key thay vì password:
          # key: ${{ secrets.PASSWORD }}
          # Nếu vẫn muốn dùng password thì:
          password: ${{ secrets.PASSWORD }}
          script: |
            set -e
            cd /srv/docker-compose/
            docker compose pull
            docker compose up --force-recreate --no-deps -d daklak-coffee-scm
